name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $ {{ matrix.node-version }}
        uses: action/setup-node@v3
        with:
        node-version: $ {{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Merge Conflict Check
        if: github.event_name == 'pull_request'
        uses: action/github-script@v5
        with:
          script: |
          const result = await github.rest.pulls.get({ owner: context.repo.owner, repo: context.repo.repo, pull_number: context.issue.number });
            if (result.data.mergeable_state === 'dirty') {
              throw new Error('Encontrado conflito no merge')
            }

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' 
    steps:
      - uses: action/checkout@v3
      - name: Use Node.js 16.x
        uses: action/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Deploy to Vercel (Dev)
        if: github.ref == 'refs/heads/master'
        run: npm run deploy_dev
      - name: Deploy to Vercel (Prod)
        if: github.ref == 'refs/heads/production'
        run: npm run deploy_prod

      